export const errorMsg = {
  content: '내용이 존재하지 않습니다.',
  content2: '내용을 작성해주시면 ',
  content3: '내용을 작성하세용 ',
  content4: '편지 수정',
  reciever: '받는 사람의 정보가 존재하지 않습니다.',
  reciever2: '받는 사람의 정보를 작성해주시면 ',
  reciever3: '받는 분을 지정하세용',
  reciever3: '받는 분을 지정하세용',
  reciever4: '받는 분 수정',
  title: '제목이 존재하지 않습니다.',
  title2: '제목을 작성해주시면 ',
  title3: '제목을 작성하세용',
  title4: '제목 수정',
  maxLength: '글자 수가 초과했습니다.',
  maxLength2: '글자 수를 줄이시면 ',
  maxLength3: '길이보단 진심이 중요하다고 생각해요',
  maxLength4: '글자 수 수정',
  DBerror: '존재하지 않는 유저입니다.',
  DBerror2: '유저를 변경하시면 ',
  DBerror3: '받는 분을 변경하세용',
  DBerror4: '받는 분 수정',
};
